### PR TITLE
Changed Variables, Methods and Classes name in ReturnBookUi.java

### PR DESCRIPTION
**Pull request by cstharosan**
Changed Variables, Methods and Classes name in ReturnBookUi.java is ready. Please review

### CODE REVIEW

**Comment by jikeshm** [comment]
@sunilrajshrestha  please review this file

**Review by sunilrajshrestha — CHANGES_REQUESTED** [review]
There is an issue on  line 81 function data type is mismatch.

**Comment by jikeshm** [comment]
Please change some codes according to the review.

**Review by jikeshm — APPROVED** [review]
all is okay

**Pull request merged**
